### ISSUE TITLE
User Profile Enhancement

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitxonline#1398]
As an instructor, I'd like to have more demographic information about my users so I can adjust my course to match the audience. 

As an educational researcher, I need more demographic information about learners so I can analyze their use of courses. 

As a marketer, I want to know more about enrolled learners and purchasers to target my messaging better. 

As a user, I don't want to share any personal information until and unless it's going to improve my learning experience. 

```[tasklist]
### Acceptance Criteria:
- [ ] https://github.com/mitodl/mitxonline/issues/1399
- [ ] https://github.com/mitodl/mitxonline/issues/1425
- [ ] https://github.com/mitodl/mitxonline/issues/1424
```

### Related issues 

- https://github.com/mitodl/mitxonline/issues/478

**Comment by pdpinch** [comment]
This feature is launched, although we still have some related issues.
