### ISSUE TITLE
Epic: Ecommerce

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#297]
### Design

![Ecommerce Data Schema(2)](https://user-images.githubusercontent.com/28598/142470042-c7afe451-484f-4713-b92c-f57a27ef54ca.png)

### Product Subsystem

The product subsystem is responsible for tracking all product-related data. Purchasable products are typically Programs and Course Runs. Pricing information is tracked as immutable data for the sake of historically accurate pricing for orders.

- [x] https://github.com/mitodl/mitxonline/issues/298
- [x] https://github.com/mitodl/mitxonline/issues/305

### Basket Subsystem

This tracks products intended to be purchased, often providing some additional state such as which runs under a program a user is purchasing.

- [x] https://github.com/mitodl/mitxonline/issues/306
- [x] https://github.com/mitodl/mitxonline/issues/307

### Order Subsystem

Orders represent a payment for some kind of product(s), these products will typically be either Programs or Course Runs. An order is marked as unfulfilled initially and then marked as fulfilled once a payment is completed. 

- [x] https://github.com/mitodl/mitxonline/issues/308

### Discount Subsystem 

Discounts will need to be provided on occasion, these give the user a reduced price for some or all products. Treating this as a discount system and not necessarily a coupon system (e.g. a coupon is a kind of discount) is a good way to frame this approach.

- [x] https://github.com/mitodl/mitxonline/issues/309
- [x] https://github.com/mitodl/mitxonline/issues/310

### Payment Subsystem

The payment subsystem takes unfulfilled orders, takes the user through payment completion, and finally marks the order as fulfilled. We historically and for the foreseeable future use CyberSource, but this should be strongly decoupled from the rest of the ecommerce system and made pluggable for future flexibility. This system would also be responsible for any webhooks/callbacks that the payment processor makes to us.

**Comment by rhysyngsun** [comment]
Closing this because we've done everything in it and I'm going to open a new product-centric epic.
