### ISSUE TITLE
Ecommerce Production Checklist

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#409]
These are items that need to be completed for production:

### Settings
- [ ] CyberSource settings and credentials

### Product Page
- [x] ~~Add real certificate icon to upgrade popup~~
- [x] Update wording on upgrade popup

**Comment by arslanashraf7** [comment]
One PR for the the ticket is at https://github.com/mitodl/salt-ops/pull/1528
