### ISSUE TITLE
Epic: Financial Aid (Flexible Pricing)

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#436]
- [ ] Learner can input financial data
- [ ] Automatic approval is supported
- [ ] If manual approval is required, prompt learner to upload it
- [ ] Admin interface to approve financial aid

**Comment by umarmughal824** [comment]
https://github.com/mitodl/mitxonline/issues/559

**Comment by rhysyngsun** [comment]
Closing this as I'm going to reorganize the issues around this.
