### ISSUE TITLE
Epic: MicroMasters user data migration

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#438]
- [ ] Migrate previous course grades
- [ ] Migrate previous exam attempts / grades
- [ ] Handle previous payments somehow
  - Manually handle this via coupons by customer service?
