### ISSUE TITLE
Epic: Order Refunds

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#442]
### Questions

- [ ] How are refunds created (e.g. in cybersource?)
- [ ] Should refunds trigger an email notification
- [ ] How are refunds represented in the UI?
