### ISSUE TITLE
Epic: Support Program Requirements

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#443]
We already have some initial support for programs in the form of a `Program` and `ProgramEnrollment` and want to expand on that to support ecommerce specifically for MicroMasters programs more thoroughly.

- [x] A Program should be able to specify required Courses
- [x] A Program should be able to specify elective Courses
- [x] ~~Program progress / completion tracking~~
- [x] Program Certificates

#### Far Future

- [ ] A Course should be able to specify prerequisite Courses

**Comment by pdpinch** [comment]
I checked all the boxes except for the "far future" one.
