### ISSUE TITLE
Epic: Paid Courses

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#562]
### Architecture

![](https://user-images.githubusercontent.com/28598/142470042-c7afe451-484f-4713-b92c-f57a27ef54ca.png)

### User Stories

- [x] Story: As a Learner I want to be able to pay for a course
  - [x] https://github.com/mitodl/mitxonline/issues/561
 
- [x] Story: As a Learner I want to be able to use a discount coupon code
  - [x] https://github.com/mitodl/mitxonline/issues/309
  - [x] https://github.com/mitodl/mitxonline/issues/310
  - [x] https://github.com/mitodl/mitxonline/issues/431
  - [x] https://github.com/mitodl/mitxonline/issues/471
  - [x] https://github.com/mitodl/mitxonline/issues/517
 
- [x] Story: As a Learner I want information on courses I've paid for
  - [x] https://github.com/mitodl/mitxonline/issues/532
 
- [x] https://github.com/mitodl/mitxonline/issues/539
  - [x] https://github.com/mitodl/mitxonline/issues/573
  - [x] https://github.com/mitodl/mitxonline/issues/542
 
- [x] https://github.com/mitodl/mitxonline/issues/543
  - [x] https://github.com/mitodl/mitxonline/issues/574
  - [x] https://github.com/mitodl/mitxonline/issues/575
  - [x] https://github.com/mitodl/mitxonline/issues/576
  - [x] https://github.com/mitodl/mitxonline/issues/577
  
- [x] https://github.com/mitodl/mitxonline/issues/570
  - [x] https://github.com/mitodl/mitxonline/issues/572
  - [x] https://github.com/mitodl/mitxonline/issues/571

**Comment by pdpinch** [comment]
All done!
