### ISSUE TITLE
Orders: Add a tracking table for course run purchases

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/mitxonline#738]
We need to be able to have a simpler way of determining which runs a learner has purchased. Currently you have to go through `User` -> `Order` -> `Line` -> `Product` -> `CourseRun`, which makes querying inefficient and messy.

I've proposed a join table that would track information on what course runs have been paid for, something like this:

```python
class PaidCourseRun(TimestampedModel):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="paid_course_runs"
    )
    course_run = models.ForeignKey(
        CourseRun, on_delete=models.CASCADE, related_name="paid_course_runs"
    )
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="paid_course_runs"
    )
```

This would simplify the joins down to `User` -> `PaidCourseRun` -> `CourseRun`.

We would only create these for orders in the `FULFILLED` or `REVIEW` state and keep the records in the event of a refund.

#### Tasks

- [x] Add a model similar to the above psuedocode
- [x] Where we currently mark an order as fulfilled or in review state, add code to create and/or update a record
- [ ] In a PR that is merged and deployed after the above logic change is deployed add a migration that backpopulates records for existing orders

**Comment by dseaton** [comment]
@rhysyngsun @rachellougee I have confirmed that this works for me. Thank you!
